#!/usr/bin/python3
print("It's a mee,Marriooo ;) "[D[D[D[D[D[D[[C[[F[F[B[B[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[Coo[C[C[C;)[F[C[C[C[C[C[C[B[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[ ")
